# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90ac0d801168533e86b54b99b65a41de4b0116fac6d3400c27c0a7cc493f8116af09a99107573dcd1e1316ef499e73476903aab9e68e9e52be4d531a256840b

test:
  secret_key_base: 298433b0735cac2a47b2ad63961cceb10a3884fbbf0894abba8086e95e1dfea81be14845d6114635458c5f4933a475287a62ad058201aa1213e67137db8a38d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
